name: CI Workflow

on:
  pull_request:
    branches:
      - 'main'

jobs:
  ci_job:
    name: CI Job
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Databricks CLI
        uses: databricks/setup-cli@main

      - name: Configure Databricks
        run: |
          # write out the profile (here called "DEV")
          cat <<EOF > ~/.databrickscfg
          [DEV]
          host = https://dbc-e3f9f6a4-4aca.cloud.databricks.com/
          account_id = ${{ secrets.ACCOUNT_ID }}
          client_id = ${{ secrets.CLIENT_ID }}
          client_secret = ${{ secrets.CLIENT_SECRET }}
          EOF

      - name: Validate DAB
        run: |
          cd HeroMotoComp
          databricks bundle validate \
            --target dev \
            --profile DEV
